### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by ismaelpedro** [JoseBarreto1/flutter_credit_card_brazilian#1]
Gostaria de agradecer pela ótima lib,  seria interessante vêla atualizada para null safety!

**Comment by jbarretojr** [comment]
Boa tarde Ismael, iremos corrigir isso essa semana, muito obrigado pelo feedback.

**Comment by ricardogobbo** [comment]
Excelente lib... Se quiser ajuda para atualizar... Estou com um projeto aqui que utilizará essa funcionalidade.

**Comment by jbarretojr** [comment]
Migrado para null safety com sucesso! Me desculpem a demora.
