### ISSUE TITLE
Diferenca do flutter_credit_card

### ISSUE THREAD

**Issue by brunodmn** [JoseBarreto1/flutter_credit_card_brazilian#2]
Gostaria de saber qual a diferença do seu pacote em relação ao [flutter_credit_card](https://pub.dev/packages/flutter_credit_card)

**Comment by jbarretojr** [comment]
Tem todas as bandeiras Brasileiras. E também, vendo a necessidade de alguns gateway nacional, quando é digitado o numero do cartão, é retornado o nome da bandeira.

**Comment by brunodmn** [comment]
Entendi @JoseBarreto1, parabéns pela iniciativa. Obrigado.
